// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105181339_AddTbProfissional")]
    partial class AddTbProfissional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.TbAlimento", b =>
                {
                    b.Property<int>("IdAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlimento"));

                    b.Property<double>("Carboidrato")
                        .HasColumnType("float");

                    b.Property<int>("IdTipoQuantidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("VitaminaA")
                        .HasColumnType("float");

                    b.Property<double>("VitaminaB")
                        .HasColumnType("float");

                    b.HasKey("IdAlimento");

                    b.ToTable("tbAlimento");
                });

            modelBuilder.Entity("WebApplication1.Models.TbAntropometria", b =>
                {
                    b.Property<int>("IdAntropometria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAntropometria"));

                    b.Property<int?>("Abdomen")
                        .HasColumnType("int");

                    b.Property<int?>("AlturaJoelho")
                        .HasColumnType("int");

                    b.Property<int?>("AuxiliarMed")
                        .HasColumnType("int");

                    b.Property<int?>("Biceps")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfAbdomen")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfBraco")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfCintura")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfQuadril")
                        .HasColumnType("int");

                    b.Property<int?>("Coxa")
                        .HasColumnType("int");

                    b.Property<int?>("Estatura")
                        .HasColumnType("int");

                    b.Property<int>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("Panturrilha")
                        .HasColumnType("int");

                    b.Property<int?>("Peitoral")
                        .HasColumnType("int");

                    b.Property<int?>("PercGordura")
                        .HasColumnType("int");

                    b.Property<int?>("PesoAtual")
                        .HasColumnType("int");

                    b.Property<int?>("PesoUsual")
                        .HasColumnType("int");

                    b.Property<int?>("Subescap")
                        .HasColumnType("int");

                    b.Property<int?>("SupraIliaca")
                        .HasColumnType("int");

                    b.Property<int?>("TipoProtocolo")
                        .HasColumnType("int");

                    b.Property<int?>("Tricipal")
                        .HasColumnType("int");

                    b.HasKey("IdAntropometria");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbAntropometria_IdHoraPaciente_Profissional");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbAntropometria_IdPaciente");

                    b.ToTable("tbAntropometria");
                });

            modelBuilder.Entity("WebApplication1.Models.TbCidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade");

                    b.HasIndex(new[] { "IdEstado" }, "IX_tbCidade_IdEstado");

                    b.ToTable("tbCidade");
                });

            modelBuilder.Entity("WebApplication1.Models.TbContrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("IdPlano")
                        .HasColumnType("int");

                    b.HasKey("IdContrato");

                    b.HasIndex(new[] { "IdPlano" }, "IX_tbContrato_IdPlano");

                    b.ToTable("tbContrato");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEscalaBristol", b =>
                {
                    b.Property<int>("IdEscalaBristol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscalaBristol"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Sangue")
                        .HasColumnType("bit");

                    b.HasKey("IdEscalaBristol");

                    b.ToTable("tbEscalaBristol");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEscalaBristolPacienteConsulta", b =>
                {
                    b.Property<int>("IdEscalaBristolPacienteConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEscalaBristol_Paciente_Consulta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscalaBristolPacienteConsulta"));

                    b.Property<int>("IdEscalaBristol")
                        .HasColumnType("int");

                    b.Property<int>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHora_Paciente_Profissional");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("IdEscalaBristolPacienteConsulta");

                    b.HasIndex(new[] { "IdEscalaBristol" }, "IX_tbEscalaBristol_Paciente_Consulta_IdEscalaBristol");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbEscalaBristol_Paciente_Consulta_IdHora_Paciente_Profissional");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbEscalaBristol_Paciente_Consulta_IdPaciente");

                    b.ToTable("tbEscalaBristol_Paciente_Consulta");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEstado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("IdEstado");

                    b.HasIndex(new[] { "IdPais" }, "IX_tbEstado_IdPais");

                    b.ToTable("tbEstado");
                });

            modelBuilder.Entity("WebApplication1.Models.TbExame", b =>
                {
                    b.Property<int>("IdExame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExame"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Grupo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdExame");

                    b.ToTable("tbExame");
                });

            modelBuilder.Entity("WebApplication1.Models.TbExameFisico", b =>
                {
                    b.Property<int>("IdExameFisico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExameFisico"));

                    b.Property<int?>("AtividadeFisica")
                        .HasColumnType("int");

                    b.Property<int?>("Diurese")
                        .HasColumnType("int");

                    b.Property<int?>("Evacuacao")
                        .HasColumnType("int");

                    b.Property<int?>("Excrecao")
                        .HasColumnType("int");

                    b.Property<bool?>("FlgDenticaoAusente")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDenticaoCompleta")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDenticaoIncompleta")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDenticaoProtese")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDisfagia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDuodenal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgEnteralExclusiva")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgEnteralParental")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgFistula")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgGastrico")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHiperemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgJejunal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgNauseas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOdinofagia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOral")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOralEnteral")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgParentalExclusiva")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgParentalOral")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPresencaFeridas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgSaidaSecrecao")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgSialorreia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgTranspilorica")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgUlcerasBucais")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgVomitos")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgXerostomia")
                        .HasColumnType("bit");

                    b.Property<int?>("Frequencia")
                        .HasColumnType("int");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int?>("FrequenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<int?>("Fumante")
                        .HasColumnType("int");

                    b.Property<int?>("Glicemia")
                        .HasColumnType("int");

                    b.Property<int?>("HoraPreferido")
                        .HasColumnType("int");

                    b.Property<int?>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    b.Property<int?>("Ingestao")
                        .HasColumnType("int");

                    b.Property<int?>("Mastigacao")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Pa")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PA");

                    b.Property<int?>("Peristalse")
                        .HasColumnType("int");

                    b.Property<int?>("Snc")
                        .HasColumnType("int")
                        .HasColumnName("SNC");

                    b.Property<int?>("Temperatura")
                        .HasColumnType("int");

                    b.Property<int?>("Tempo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoAcesso")
                        .HasColumnType("int");

                    b.Property<string>("TipoAtividadeFisica")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("TipoDiurese")
                        .HasColumnType("int");

                    b.Property<int?>("TipoEvacuacao")
                        .HasColumnType("int");

                    b.HasKey("IdExameFisico");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbExameFisico_IdHoraPaciente_Profissional");

                    b.ToTable("tbExameFisico");
                });

            modelBuilder.Entity("WebApplication1.Models.TbExameXPacientes", b =>
                {
                    b.Property<int>("IdExameXPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdExame_X_Paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExameXPaciente"));

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdExame")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("IdExameXPaciente");

                    b.HasIndex(new[] { "IdExame" }, "IX_tbExame_X_Pacientes_IdExame");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbExame_X_Pacientes_IdPaciente");

                    b.ToTable("tbExame_X_Pacientes");
                });

            modelBuilder.Entity("WebApplication1.Models.TbGrupoPatologico", b =>
                {
                    b.Property<int>("IdGrupoPatologico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoPatologico"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdGrupoPatologico");

                    b.ToTable("tbGrupoPatologico");
                });

            modelBuilder.Entity("WebApplication1.Models.TbGrupoPatologicoXPatologia", b =>
                {
                    b.Property<int>("IdPatologiaXGrupoPatologico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPatologia_X_GrupoPatologico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatologiaXGrupoPatologico"));

                    b.Property<int>("IdGrupoPatologico")
                        .HasColumnType("int");

                    b.Property<int>("IdPatologia")
                        .HasColumnType("int");

                    b.HasKey("IdPatologiaXGrupoPatologico");

                    b.HasIndex(new[] { "IdGrupoPatologico" }, "IX_tbGrupoPatologico_X_Patologia_IdGrupoPatologico");

                    b.HasIndex(new[] { "IdPatologia" }, "IX_tbGrupoPatologico_X_Patologia_IdPatologia");

                    b.ToTable("tbGrupoPatologico_X_Patologia");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoriaPatologica", b =>
                {
                    b.Property<int>("IdHistoriaPatologica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoriaPatologica"));

                    b.Property<bool?>("FlgAnemias")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvc")
                        .HasColumnType("bit")
                        .HasColumnName("FlgAVC");

                    b.Property<bool?>("FlgCirurgias")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencaHepatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencaRenal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencasAutoImunes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencasCardiacas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencasPulmonares")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHas")
                        .HasColumnType("bit")
                        .HasColumnName("FlgHAS");

                    b.Property<bool?>("FlgHipercolesterolemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHipertrigliciridemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHiperuricemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgNeoplasia")
                        .HasColumnType("bit");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatologia")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdHistoriaPatologica");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoriaPatologica_IdPaciente");

                    b.HasIndex(new[] { "IdPatologia" }, "IX_tbHistoriaPatologica_IdPatologia");

                    b.ToTable("tbHistoriaPatologica");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoricoAlimentarNutricional", b =>
                {
                    b.Property<int>("IdHistAlimentarNutricional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistAlimentarNutricional"));

                    b.Property<string>("DescDietas")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescExercicios")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescIntoleranciaAlimentar")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescMedicamentos")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescOutros")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("FaseObesidadePerdaPeso")
                        .HasColumnType("int");

                    b.Property<bool?>("FlgDietas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgExercicios")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIntoleanciaAlimentar")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgMedicamentos")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOutros")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPerdaGanhoPeso")
                        .HasColumnType("bit");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("ModismosAlimentares")
                        .HasColumnType("int");

                    b.Property<int?>("MotivacaoTratamento")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PesoMax")
                        .HasColumnType("int");

                    b.Property<int?>("PesoMaxIdade")
                        .HasColumnType("int");

                    b.Property<int?>("PesoMin")
                        .HasColumnType("int");

                    b.Property<int?>("PesoMinIdade")
                        .HasColumnType("int");

                    b.HasKey("IdHistAlimentarNutricional");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoricoAlimentarNutricional_IdPaciente");

                    b.ToTable("tbHistoricoAlimentarNutricional");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoricoDoencaAtual", b =>
                {
                    b.Property<int>("IdHda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHDA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHda"));

                    b.Property<int?>("Cirurgia")
                        .HasColumnType("int");

                    b.Property<string>("Historico")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatologia")
                        .HasColumnType("int");

                    b.Property<int?>("Infeccao")
                        .HasColumnType("int");

                    b.Property<int?>("Metastase")
                        .HasColumnType("int");

                    b.Property<int?>("Neoplasia")
                        .HasColumnType("int");

                    b.Property<string>("ObsMetastase")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ObsNeoplasia")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ObsQueimadura")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Outros")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Queimadura")
                        .HasColumnType("int");

                    b.Property<int?>("Trauma")
                        .HasColumnType("int");

                    b.HasKey("IdHda");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoricoDoencaAtual_IdPaciente");

                    b.HasIndex(new[] { "IdPatologia" }, "IX_tbHistoricoDoencaAtual_IdPatologia");

                    b.ToTable("tbHistoricoDoencaAtual");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoricoSocialAlimentar", b =>
                {
                    b.Property<int>("IdHistSocialAlimentar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistSocialAlimentar"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int?>("CompraFeita")
                        .HasColumnType("int");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("FlgAvosCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvosDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvosHas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvosObesidade")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgCafe")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgEtilismo")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosHas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosObesidade")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeHas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeObesidade")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgTabagismo")
                        .HasColumnType("bit");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompraAlimento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeCozinhaAlimento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeRealizaRefeicao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NroPessoasRes")
                        .HasColumnType("int");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("QtdCafeDia")
                        .HasColumnType("int");

                    b.Property<int?>("QtdEtilismoDia")
                        .HasColumnType("int");

                    b.Property<int?>("QtdTabagismoDia")
                        .HasColumnType("int");

                    b.Property<decimal?>("RendaFamiliar")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("IdHistSocialAlimentar");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoricoSocialAlimentar_IdPaciente");

                    b.ToTable("tbHistoricoSocialAlimentar");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHoraPacienteProfissional", b =>
                {
                    b.Property<int>("IdHoraPacienteProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoraPacienteProfissional"));

                    b.Property<bool>("Compareceu")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DataConsulta")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFimIndividual")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("HoraInicioIndividual")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<bool>("PrimeiraConculta")
                        .HasColumnType("bit");

                    b.Property<string>("Resumo")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdHoraPacienteProfissional");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHoraPaciente_Profissional_IdPaciente");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbHoraPaciente_Profissional_IdProfissional");

                    b.ToTable("tbHoraPaciente_Profissional");
                });

            modelBuilder.Entity("WebApplication1.Models.TbMedicoPaciente", b =>
                {
                    b.Property<int>("IdMedicoPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedico_Paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicoPaciente"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoResumida")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.HasKey("IdMedicoPaciente");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbMedico_Paciente_IdPaciente");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbMedico_Paciente_IdProfissional");

                    b.ToTable("tbMedico_Paciente");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPaciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CPF");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Etnia")
                        .HasColumnType("int");

                    b.Property<bool?>("FlgAtleta")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgGestante")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Profissao")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("RG");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("TelCelular")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TelComercial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TelResidencial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdPaciente");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbPaciente_IdCidade");

                    b.ToTable("tbPaciente");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("IdPais");

                    b.ToTable("tbPais");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPatologia", b =>
                {
                    b.Property<int>("IdPatologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatologia"));

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPatologia");

                    b.ToTable("tbPatologia");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPergunta", b =>
                {
                    b.Property<int>("IdPergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPergunta"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdPergunta");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbPergunta_IdProfissional");

                    b.ToTable("tbPergunta");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPlano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Validade")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPlano");

                    b.ToTable("tbPlano");
                });

            modelBuilder.Entity("WebApplication1.Models.TbProfissional", b =>
                {
                    b.Property<int>("IdProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfissional"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CPF");

                    b.Property<string>("CrmCrn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CRM_CRN");

                    b.Property<string>("Ddd1")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("DDD1");

                    b.Property<string>("Ddd2")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("DDD2");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoAcesso")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoProfissional")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Telefone1")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Telefone2")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdProfissional");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbProfissional_IdCidade");

                    b.HasIndex(new[] { "IdContrato" }, "IX_tbProfissional_IdContrato");

                    b.HasIndex(new[] { "IdTipoAcesso" }, "IX_tbProfissional_IdTipoAcesso");

                    b.ToTable("tbProfissional");
                });

            modelBuilder.Entity("WebApplication1.Models.TbRastreamentoMetabolico", b =>
                {
                    b.Property<int>("IdRastreamentoMetabolico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRastreamentoMetabolico"));

                    b.Property<int>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    b.Property<int>("IdRastreamentoResposta")
                        .HasColumnType("int");

                    b.Property<string>("ObsGeral")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.HasKey("IdRastreamentoMetabolico");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbRastreamentoMetabolico_IdHoraPaciente_Profissional");

                    b.HasIndex(new[] { "IdRastreamentoResposta" }, "IX_tbRastreamentoMetabolico_IdRastreamentoResposta");

                    b.ToTable("tbRastreamentoMetabolico");
                });

            modelBuilder.Entity("WebApplication1.Models.TbRastreamentoResposta", b =>
                {
                    b.Property<int>("IdRastreamentoResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRastreamentoResposta"));

                    b.Property<int>("IdParteCorpo")
                        .HasColumnType("int");

                    b.Property<int>("IdPergunta")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("VlrRespota")
                        .HasColumnType("int");

                    b.HasKey("IdRastreamentoResposta");

                    b.HasIndex(new[] { "IdPergunta" }, "IX_tbRastreamentoResposta_IdPergunta");

                    b.ToTable("tbRastreamentoResposta");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaAlimentarPadrao", b =>
                {
                    b.Property<int>("IdReceitaAlimentarPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaAlimentarPadrao"));

                    b.Property<int?>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdReceitaAlimentarPadrao");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbReceitaAlimentarPadrao_IdProfissional");

                    b.ToTable("tbReceitaAlimentarPadrao");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaAlimentarPadraoXAlimento", b =>
                {
                    b.Property<int>("IdReceitaAlimentarPadraoXAlimentoXQuantidadeAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdReceitaAlimentarPadrao_X_Alimento_X_QuantidadeAlimento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaAlimentarPadraoXAlimentoXQuantidadeAlimento"));

                    b.Property<int>("IdAlimento")
                        .HasColumnType("int");

                    b.Property<int>("IdQuantidadeAlimento")
                        .HasColumnType("int");

                    b.Property<int>("IdReceitaAlimentarPadrao")
                        .HasColumnType("int");

                    b.Property<string>("Periodicidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QuantoTempo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdReceitaAlimentarPadraoXAlimentoXQuantidadeAlimento");

                    b.HasIndex(new[] { "IdAlimento" }, "IX_tbReceitaAlimentarPadrao_X_Alimento_IdAlimento");

                    b.HasIndex(new[] { "IdReceitaAlimentarPadrao" }, "IX_tbReceitaAlimentarPadrao_X_Alimento_IdReceitaAlimentarPadrao");

                    b.ToTable("tbReceitaAlimentarPadrao_X_Alimento");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaMedicaPadrao", b =>
                {
                    b.Property<int>("IdReceitaMedicaPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaMedicaPadrao"));

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdReceitaMedicaPadrao");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbReceitaMedicaPadrao_IdProfissional");

                    b.ToTable("tbReceitaMedicaPadrao");
                });

            modelBuilder.Entity("WebApplication1.Models.TbTipoAcesso", b =>
                {
                    b.Property<int>("IdTipoAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoAcesso"));

                    b.Property<bool>("FlagAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTipoAcesso");

                    b.ToTable("tbTipoAcesso");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.TbAntropometria", b =>
                {
                    b.HasOne("WebApplication1.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbAntropometria")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbAntropometria")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdHoraPacienteProfissionalNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbCidade", b =>
                {
                    b.HasOne("WebApplication1.Models.TbEstado", "IdEstadoNavigation")
                        .WithMany("TbCidade")
                        .HasForeignKey("IdEstado");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbContrato", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPlano", "IdPlanoNavigation")
                        .WithMany("TbContrato")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPlanoNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEscalaBristolPacienteConsulta", b =>
                {
                    b.HasOne("WebApplication1.Models.TbEscalaBristol", "IdEscalaBristolNavigation")
                        .WithMany("TbEscalaBristolPacienteConsulta")
                        .HasForeignKey("IdEscalaBristol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbEscalaBristolPacienteConsulta")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbEscalaBristolPacienteConsulta")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEscalaBristolNavigation");

                    b.Navigation("IdHoraPacienteProfissionalNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEstado", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPais", "IdPaisNavigation")
                        .WithMany("TbEstado")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbExameFisico", b =>
                {
                    b.HasOne("WebApplication1.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbExameFisico")
                        .HasForeignKey("IdHoraPacienteProfissional");

                    b.Navigation("IdHoraPacienteProfissionalNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbExameXPacientes", b =>
                {
                    b.HasOne("WebApplication1.Models.TbExame", "IdExameNavigation")
                        .WithMany("TbExameXPacientes")
                        .HasForeignKey("IdExame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbExameXPacientes")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdExameNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbGrupoPatologicoXPatologia", b =>
                {
                    b.HasOne("WebApplication1.Models.TbGrupoPatologico", "IdGrupoPatologicoNavigation")
                        .WithMany("TbGrupoPatologicoXPatologia")
                        .HasForeignKey("IdGrupoPatologico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbPatologia", "IdPatologiaNavigation")
                        .WithMany("TbGrupoPatologicoXPatologia")
                        .HasForeignKey("IdPatologia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdGrupoPatologicoNavigation");

                    b.Navigation("IdPatologiaNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoriaPatologica", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoriaPatologica")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbPatologia", "IdPatologiaNavigation")
                        .WithMany("TbHistoriaPatologica")
                        .HasForeignKey("IdPatologia");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdPatologiaNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoricoAlimentarNutricional", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoricoAlimentarNutricional")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoricoDoencaAtual", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoricoDoencaAtual")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbPatologia", "IdPatologiaNavigation")
                        .WithMany("TbHistoricoDoencaAtual")
                        .HasForeignKey("IdPatologia");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdPatologiaNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHistoricoSocialAlimentar", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoricoSocialAlimentar")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHoraPacienteProfissional", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHoraPacienteProfissional")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbHoraPacienteProfissional")
                        .HasForeignKey("IdProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbMedicoPaciente", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbMedicoPaciente")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbMedicoPaciente")
                        .HasForeignKey("IdProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPaciente", b =>
                {
                    b.HasOne("WebApplication1.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany("TbPaciente")
                        .HasForeignKey("IdCidade");

                    b.Navigation("IdCidadeNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPergunta", b =>
                {
                    b.HasOne("WebApplication1.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbPergunta")
                        .HasForeignKey("IdProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbProfissional", b =>
                {
                    b.HasOne("WebApplication1.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbContrato", "IdContratoNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbTipoAcesso", "IdTipoAcessoNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdTipoAcesso");

                    b.Navigation("IdCidadeNavigation");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdTipoAcessoNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbRastreamentoMetabolico", b =>
                {
                    b.HasOne("WebApplication1.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbRastreamentoMetabolico")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbRastreamentoResposta", "IdRastreamentoRespostaNavigation")
                        .WithMany("TbRastreamentoMetabolico")
                        .HasForeignKey("IdRastreamentoResposta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdHoraPacienteProfissionalNavigation");

                    b.Navigation("IdRastreamentoRespostaNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbRastreamentoResposta", b =>
                {
                    b.HasOne("WebApplication1.Models.TbPergunta", "IdPerguntaNavigation")
                        .WithMany("TbRastreamentoResposta")
                        .HasForeignKey("IdPergunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPerguntaNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaAlimentarPadrao", b =>
                {
                    b.HasOne("WebApplication1.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbReceitaAlimentarPadrao")
                        .HasForeignKey("IdProfissional");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaAlimentarPadraoXAlimento", b =>
                {
                    b.HasOne("WebApplication1.Models.TbAlimento", "IdAlimentoNavigation")
                        .WithMany("TbReceitaAlimentarPadraoXAlimento")
                        .HasForeignKey("IdAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TbReceitaAlimentarPadrao", "IdReceitaAlimentarPadraoNavigation")
                        .WithMany("TbReceitaAlimentarPadraoXAlimento")
                        .HasForeignKey("IdReceitaAlimentarPadrao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAlimentoNavigation");

                    b.Navigation("IdReceitaAlimentarPadraoNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaMedicaPadrao", b =>
                {
                    b.HasOne("WebApplication1.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbReceitaMedicaPadrao")
                        .HasForeignKey("IdProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.TbAlimento", b =>
                {
                    b.Navigation("TbReceitaAlimentarPadraoXAlimento");
                });

            modelBuilder.Entity("WebApplication1.Models.TbCidade", b =>
                {
                    b.Navigation("TbPaciente");

                    b.Navigation("TbProfissional");
                });

            modelBuilder.Entity("WebApplication1.Models.TbContrato", b =>
                {
                    b.Navigation("TbProfissional");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEscalaBristol", b =>
                {
                    b.Navigation("TbEscalaBristolPacienteConsulta");
                });

            modelBuilder.Entity("WebApplication1.Models.TbEstado", b =>
                {
                    b.Navigation("TbCidade");
                });

            modelBuilder.Entity("WebApplication1.Models.TbExame", b =>
                {
                    b.Navigation("TbExameXPacientes");
                });

            modelBuilder.Entity("WebApplication1.Models.TbGrupoPatologico", b =>
                {
                    b.Navigation("TbGrupoPatologicoXPatologia");
                });

            modelBuilder.Entity("WebApplication1.Models.TbHoraPacienteProfissional", b =>
                {
                    b.Navigation("TbAntropometria");

                    b.Navigation("TbEscalaBristolPacienteConsulta");

                    b.Navigation("TbExameFisico");

                    b.Navigation("TbRastreamentoMetabolico");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPaciente", b =>
                {
                    b.Navigation("TbAntropometria");

                    b.Navigation("TbEscalaBristolPacienteConsulta");

                    b.Navigation("TbExameXPacientes");

                    b.Navigation("TbHistoriaPatologica");

                    b.Navigation("TbHistoricoAlimentarNutricional");

                    b.Navigation("TbHistoricoDoencaAtual");

                    b.Navigation("TbHistoricoSocialAlimentar");

                    b.Navigation("TbHoraPacienteProfissional");

                    b.Navigation("TbMedicoPaciente");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPais", b =>
                {
                    b.Navigation("TbEstado");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPatologia", b =>
                {
                    b.Navigation("TbGrupoPatologicoXPatologia");

                    b.Navigation("TbHistoriaPatologica");

                    b.Navigation("TbHistoricoDoencaAtual");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPergunta", b =>
                {
                    b.Navigation("TbRastreamentoResposta");
                });

            modelBuilder.Entity("WebApplication1.Models.TbPlano", b =>
                {
                    b.Navigation("TbContrato");
                });

            modelBuilder.Entity("WebApplication1.Models.TbProfissional", b =>
                {
                    b.Navigation("TbHoraPacienteProfissional");

                    b.Navigation("TbMedicoPaciente");

                    b.Navigation("TbPergunta");

                    b.Navigation("TbReceitaAlimentarPadrao");

                    b.Navigation("TbReceitaMedicaPadrao");
                });

            modelBuilder.Entity("WebApplication1.Models.TbRastreamentoResposta", b =>
                {
                    b.Navigation("TbRastreamentoMetabolico");
                });

            modelBuilder.Entity("WebApplication1.Models.TbReceitaAlimentarPadrao", b =>
                {
                    b.Navigation("TbReceitaAlimentarPadraoXAlimento");
                });

            modelBuilder.Entity("WebApplication1.Models.TbTipoAcesso", b =>
                {
                    b.Navigation("TbProfissional");
                });
#pragma warning restore 612, 618
        }
    }
}
